version: '3.8'
name: projectname
services:
    frontend:
        image: ../path/to/repo/frontend:latest
        build: .
        container_name: projectname-frontend
        restart: unless-stopped
        # depends_on:
        #     - backend  # Wait for backend service to start
        ports:
            - "80:80"  # HTTP protocol connection
